### ISSUE TITLE
(Invalid) script produces an unexpected exception

### ISSUE THREAD

**Issue by chrissiwaffler** [OpShin/opshin#175]
**Describe the bug**
compiling or linting script produces an unexpected error:
```
#!/usr/bin/env -S opshin eval minting
from opshin.prelude import *

def validator():
    return True
```

running this with `opshin build spending broken.py` produces:
```
Traceback (most recent call last):
  File "/Users/chrissi/miniconda3/bin/opshin", line 8, in <module>
    sys.exit(main())
  File "/Users/chrissi/miniconda3/lib/python3.10/site-packages/opshin/__main__.py", line 225, in main
    check_params(
  File "/Users/chrissi/miniconda3/lib/python3.10/site-packages/opshin/__main__.py", line 128, in check_params
    onchain_params[-1] == ScriptContext
IndexError: list index out of range
```

note: this also happens when running with `minting` **but not** when running with `any`

**Comment by chrissiwaffler** [comment]
maybe we should also add a test case to cover this specific contract

**Comment by nielstron** [comment]
> maybe we should also add a test case to cover this specific contract

Good idea. Not sure however how to best cover this though
