### ISSUE TITLE
Error when causing errors in list comprehensions

### ISSUE THREAD

**Issue by nielstron** [OpShin/opshin#195]
**Describe the bug**
When compiling the following program

```
# test.py
a = [a for a, b in [(1, 2)]]
```

with `opshin build lib test.py` the following trace is printed

```
Traceback (most recent call last):
  File "...opshin/util.py", line 528, in visit
    return super().visit(node)
  File "...opshin/typed_ast.py", line 1309, in visit
    return visitor(node)
  File "...opshin/type_inference.py", line 619, in visit_comprehension
    raise NotImplementedError(
NotImplementedError: Type deconstruction in for loops is not supported yet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...opshin/__main__.py", line 224, in perform_command
    code = compiler.compile(
  File "...opshin/compiler.py", line 999, in compile
    prog = s.visit(prog)
  File "...opshin/util.py", line 531, in visit
    raise e
  File "...opshin/util.py", line 528, in visit
    return super().visit(node)
  File "...opshin/typed_ast.py", line 1309, in visit
    return visitor(node)
  File "...opshin/type_inference.py", line 412, in visit_Module
    tm.body = [self.visit(n) for n in node.body]
  File "...opshin/type_inference.py", line 412, in <listcomp>
    tm.body = [self.visit(n) for n in node.body]
  File "...opshin/util.py", line 531, in visit
    raise e
  File "...opshin/util.py", line 528, in visit
    return super().visit(node)
  File "...opshin/typed_ast.py", line 1309, in visit
    return visitor(node)
  File "...opshin/type_inference.py", line 236, in visit_Assign
    typed_ass.value: TypedExpression = self.visit(node.value)
  File "...opshin/util.py", line 531, in visit
    raise e
  File "...opshin/util.py", line 528, in visit
    return super().visit(node)
  File "...opshin/typed_ast.py", line 1309, in visit
    return visitor(node)
  File "...opshin/type_inference.py", line 649, in visit_ListComp
    typed_listcomp.generators = [self.visit(s) for s in node.generators]
  File "...opshin/type_inference.py", line 649, in <listcomp>
    typed_listcomp.generators = [self.visit(s) for s in node.generators]
  File "...opshin/util.py", line 532, in visit
    raise CompilerError(e, node, self.step)
opshin.util.CompilerError: (NotImplementedError('Type deconstruction in for loops is not supported yet'), <ast.comprehension object at 0x7f6d573b2bc0>, 'Static Type Inference')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/niels/.cache/pypoetry/virtualenvs/tminus1-smart-contract-w9-IdXo4-py3.10/bin/opshin", line 8, in <module>
    sys.exit(main())
  File "...opshin/__main__.py", line 388, in main
    perform_command(args)
  File "...opshin/__main__.py", line 237, in perform_command
    start_line = c.node.lineno - 1
AttributeError: 'comprehension' object has no attribute 'lineno'

```
**To Reproduce**
See above

**Expected behavior**
Should not trigger the lineno error

**Comment by chrissiwaffler** [comment]
@nielstron I also have another `lineno`-error:

```
Traceback (most recent call last):
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 823, in visit_Attribute
    tp.typ = owner.attribute_type(node.attr)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/types.py", line 954, in attribute_type
    return self.typ.attribute_type(attr)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/types.py", line 30, in attribute_type
    raise TypeInferenceError(
opshin.types.TypeInferenceError: Object of type <class 'opshin.types.AnyType'> does not have attribute CONSTR_ID

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/__main__.py", line 239, in perform_command
    code = compiler.compile(
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/compiler.py", line 1040, in compile
    prog = s.visit(prog)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 617, in visit_Module
    tm.body = self.visit_sequence(node.body)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 383, in visit_sequence
    stmt = self.visit(n)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 598, in visit_FunctionDef
    tfd.body = self.visit_sequence(node.body)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 383, in visit_sequence
    stmt = self.visit(n)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 480, in visit_If
    typed_if.body = self.visit_sequence(node.body)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 383, in visit_sequence
    stmt = self.visit(n)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 480, in visit_If
    typed_if.body = self.visit_sequence(node.body)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 383, in visit_sequence
    stmt = self.visit(n)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 828, in visit_Assert
    ta.test = self.visit(node.test)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 765, in visit_Call
    tc.args = [self.visit(a) for a in node.args]
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 765, in <listcomp>
    tc.args = [self.visit(a) for a in node.args]
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 769, in visit_Call
    ntc = self.visit(
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 552, in visit_Compare
    typed_cmp.left = self.visit(node.left)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/util.py", line 54, in visit
    raise CompilerError(e, node, self.step)
opshin.util.CompilerError: (TypeInferenceError("Object of type <class 'opshin.types.AnyType'> does not have attribute CONSTR_ID"), <ast.Attribute object at 0x104f048e0>, 'Static Type Inference')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/bin/opshin", line 8, in <module>
    sys.exit(main())
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/__main__.py", line 403, in main
    perform_command(args)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/smart-contracts-az_CYpVN-py3.10/lib/python3.10/site-packages/opshin/__main__.py", line 252, in perform_command
    start_line = c.node.lineno - 1
AttributeError: 'Attribute' object has no attribute 'lineno'
```

**Comment by nielstron** [comment]
@chrissiwaffler Thanks for the additional example! Could you please provide me with a minimal breaking example that causes this behavior?
