### ISSUE TITLE
Error when checking instance of Datum containing Union Type

### ISSUE THREAD

**Issue by chrissiwaffler** [OpShin/opshin#242]
**Describe the bug**
A custom datum gets defined containing a Union type
When checking / typecasting using `isinstance` using the custom datum, the error `AttributeError: 'Attribute' object has no attribute 'lineno'` is given.

**To Reproduce**

use the following minimal code to reproduce the error:
```
#! /usr/bin/env -S opshin eval spending
from dataclasses import dataclass
from opshin.prelude import *


@dataclass
class ExactInOrder(PlutusData):
    CONSTR_ID = 0


@dataclass
class ExactOutOrder(PlutusData):
    CONSTR_ID = 1


OrderStep = Union[
    ExactInOrder,
    ExactOutOrder,
]


@dataclass
class OrderDatum(PlutusData):
    orderStep: OrderStep


def validator(_: Datum, __: None, context: ScriptContext) -> None:
    output = context.tx_info.outputs[0]
    output_datum = output.datum
    assert isinstance(output_datum, SomeOutputDatum)

    output_datum_value = output_datum.datum
    assert isinstance(output_datum_value, OrderDatum)
```

complete error output when trying to build the validator:
```
opshin build spending validator.py 
Traceback (most recent call last):
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 823, in visit_Attribute
    tp.typ = owner.attribute_type(node.attr)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/types.py", line 954, in attribute_type
    return self.typ.attribute_type(attr)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/types.py", line 30, in attribute_type
    raise TypeInferenceError(
opshin.types.TypeInferenceError: Object of type <class 'opshin.types.AnyType'> does not have attribute CONSTR_ID

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/__main__.py", line 239, in perform_command
    code = compiler.compile(
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/compiler.py", line 1079, in compile
    prog = s.visit(prog)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 617, in visit_Module
    tm.body = self.visit_sequence(node.body)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 383, in visit_sequence
    stmt = self.visit(n)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 598, in visit_FunctionDef
    tfd.body = self.visit_sequence(node.body)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 383, in visit_sequence
    stmt = self.visit(n)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 828, in visit_Assert
    ta.test = self.visit(node.test)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 765, in visit_Call
    tc.args = [self.visit(a) for a in node.args]
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 765, in <listcomp>
    tc.args = [self.visit(a) for a in node.args]
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 769, in visit_Call
    ntc = self.visit(
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 53, in visit
    raise e
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 50, in visit
    return super().visit(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 24, in visit
    return visitor(node)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/type_inference.py", line 552, in visit_Compare
    typed_cmp.left = self.visit(node.left)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/util.py", line 54, in visit
    raise CompilerError(e, node, self.step)
opshin.util.CompilerError: (TypeInferenceError("Object of type <class 'opshin.types.AnyType'> does not have attribute CONSTR_ID"), <ast.Attribute object at 0x109cbfa90>, 'Static Type Inference')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/bin/opshin", line 8, in <module>
    sys.exit(main())
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/__main__.py", line 403, in main
    perform_command(args)
  File "/Users/chrissi/Library/Caches/pypoetry/virtualenvs/dex-datum-_CAxKWgd-py3.10/lib/python3.10/site-packages/opshin/__main__.py", line 252, in perform_command
    start_line = c.node.lineno - 1
AttributeError: 'Attribute' object has no attribute 'lineno'
```

**Expected behavior**
should compile the script or give the user information about what he did wrong.

**Desktop (please complete the following information):**
opshin version: 0.16.1 from branch `dev` with latest commit: `d7e48a7`

**Additional context**
I mentioned this error previously on a maybe related issue: https://github.com/OpShin/opshin/issues/195#issuecomment-1668660829, but didn't provide more steps to reproduce the issue.

**Comment by nielstron** [comment]
Thanks for the details! I will try to reproduce with d7e48a7b9b573a66a1898962c404b754990281d9

**Comment by chrissiwaffler** [comment]
for anybody else having this issue:

doing  a cast with  `output_datum_value: OrderDatum = output_datum_value`
instead of doing `assert isinstance(output_datum_value, OrderDatum)` 
still works

**Comment by nielstron** [comment]
This is actually the intended way of doing the cast. But the error thrown should be properly displayed

**Comment by nielstron** [comment]
I was able to reduce the MBE to

```python
#! /usr/bin/env -S opshin eval spending
from dataclasses import dataclass
from pycardano import Datum as Anything, PlutusData
from typing import Dict, List, Union


@dataclass
class ExactInOrder(PlutusData):
    CONSTR_ID = 0


def validator(d: Anything) -> None:
    assert isinstance(d, ExactInOrder)
```
